### ISSUE TITLE
Can we allow !rs command access for everyone in public? 

### ISSUE THREAD

**Issue by themegabyte** [cato-a/CoDaM_MiscMod#25]
Basically adding 56 to this: https://github.com/cato-a/CoDaM_MiscMod/blob/b627910e5541db70aabef69bf95ead6af7e06fd8/___CoDaM_MiscMod/codam/_mm_commands.gsc#L29

```diff
-level.perms["default"] = codam\_mm_mmm::strTok("0-4:25:26", ":"); // pff xD
+level.perms["default"] = codam\_mm_mmm::strTok("0-4:25:26:56", ":"); // pff xD
```

:)

**Comment by cato-a** [comment]
Hi, you can override the defaults in the MiscMod settings.

```cfg
set scr_mm_groups "default"
set scr_mm_perms_default "1-4:25-26:56"  
```

https://cod.pm/guide/d0da8d/installing-and-configuring-codam-miscmod

:)

**Comment by themegabyte** [comment]
thank you for your response.

My bad I forgot to share. I tried! I will try again and let you know. :)

**Comment by themegabyte** [comment]
It seems like I have to include default as a group for it to pick up the permissions. Fair enough.

```
set scr_mm_groups "owner;public;default" // <- must
// then this will work
set scr_mm_perms_default "1-4:6:25-26:56"
```

Thank you! :)

EDIT: haha goofed, basically what you said.
