### ISSUE TITLE
Sometimes the server crash (at the end of map I think)

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#3]
Hello

Sometimes my server crash, I think it's at the end of maps (I use custom maps), I also think it happens only when there are more than 1 player in the server/when there are scores... but not sure about that.

I struggle to reproduce the issue...

Here is a screenshot of what I've been able to get from logs, I will try to get more, if someone has and idea about how to, please share.

![crash](https://user-images.githubusercontent.com/55389708/213767962-34bc40c4-3e00-4647-bea2-ddda8511019f.png)

Does someone knows why I have this crash sometimes ?

Please help me

**Comment by cato-a** [comment]
We troubleshooted this to be a case where `developer 1` was enabled. With `developer 0` there are no issues.
