### ISSUE TITLE
"scr_mm_nnn" does not apply

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#4]
Hello
Leaving the default value, or using the value "20"
A wait time of around 4 minutes is required for the 999 clone to disappear

I don't know if other servers are experiencing the same situation

Am I missing something ?

Please help me

**Comment by cato-a** [comment]
Hi, `scr_mm_nnn` is disabled when `sv_allowDownload` is enabled because clients downloading maps are 999 during the download.

I updated the `MiscMod.cfg` with this information. https://github.com/cato-a/CoDaM_MiscMod/commit/926b42962befa350ae86af1ab6c979b42faaa346

**Comment by ghost** [comment]
My clients are displayed with a ping of "-1" during downloads as you could see in the following screenshot
![-1 ping during download](https://user-images.githubusercontent.com/55389708/215122500-8dec63d1-4a35-4680-a177-afb85104790f.jpg)

Server is started using `+set fs_game`

Am I missing something ?

I care because clients are unable to join when having a 999 clone in the server, and it happens often when joining for the first time after `/reconnect` because of a download not starting.
__________________________
I think I noticed that clients get 999 ping when doing ALT+ENTER
hoping this information could be helpful if not noticed
__________________________

**Comment by cato-a** [comment]
You can try edit this line:

https://github.com/cato-a/CoDaM_MiscMod/blob/926b42962befa350ae86af1ab6c979b42faaa346/___CoDaM_MiscMod/codam/miscmod.gsc#L294

To:

```cpp
if(kickout == 0)
```

And report back if you are able to download maps while 999 kicker with lets say 60 seconds. You should set 60 seconds to give time for slow clients to connect and not get kicked.

**Comment by ghost** [comment]
@cato-a 

I edited the line and set scr_mm_nnn to 60 seconds

Then client was still able to fully download a pk3 of ~10mb at ~10kb/s, for about ten minutes.
Tried several times, didn't get disconnected.

scr_mm_nnn is now applied, verified using several values.

thank you Cato, and i apologize I didn't know

**Comment by cato-a** [comment]
It turns out that clients are always 999 (but sometimes shown as -1 in the scoreboard).

Changes has been reverted. https://github.com/cato-a/CoDaM_MiscMod/commit/3208abd772061fe367fceed713ccac0739d884de
