### ISSUE TITLE
"replay this map" doesn't indicate gametype

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#5]
Hello

A map is included twice in the `mapRotation` of my server, with different `gametype`

On this map, `mapvote` displays twice "replay this map" without indicating `gametype`, as you could see on the following screenshot :

![missing gametype replay](https://user-images.githubusercontent.com/55389708/218299193-e74ade33-262a-4aaa-a6e8-88d93281a74e.png)

On other maps, `mapvote` displays twice the map, indicating `gametype`.

Could you do something for that please ?

**Comment by cato-a** [comment]
Hi, you probably have too few maps left in the rotation. Add one more map to the rotation and you should have 4 maps displayed. You need to have at least 4 unique maps left in the rotation.

**Comment by ghost** [comment]
@cato-a 
There are 4 unique maps in the rotation

Here it is : `gametype dm map zh_king map mp_harbor gametype tdm map suldal_harbor gametype sd map german_town map zh_king`

**Comment by cato-a** [comment]
Yes you have 4 unique maps, but one map is used for "replay this map", so you only have 3 unique maps left in the rotation.

**Comment by ghost** [comment]
I just realized that the two replay choices are the same gametype.

I'm trying to change that and will make a pull request if I succeed.

**Comment by cato-a** [comment]
There is no issue here. You need to add 1 more map so that you have enough unique maps in the rotation (4 unique maps in rotation + "replay this map" = 5 unique maps in total). For the rotation to work you need to have a minimum of 5 unique maps.

**Comment by ghost** [comment]
For my servers, I want all the possibilities to be displayed in mapvote, so I have 5 in maprotation.

Here is how it looks on the maps that are not the one included twice :

![ok](https://user-images.githubusercontent.com/55389708/219015787-f5b74c0e-6cbf-41a1-bdc1-0c174dbc40e8.png)
Exactly what I want.

And here is how it looks on the map included twice : 

![not ok](https://user-images.githubusercontent.com/55389708/219016142-5a20842f-6616-4dcb-9ffa-30c9931f2f21.png)
_______

For me it's a problem that's why I try to modify the behavior.

**Comment by cato-a** [comment]
Yes, I understand, but MiscMod support unique maps, not duplicate maps. The bug is rather duplicate maps show up in the vote if the gametype is different.  So "replay this map" and "mystery map" will remove any non-unique maps.

So to do what you want you must edit `_mm_mapvote.gsc`

Find this code and comment it out/delete (line 465/466):

```gsc
    if(codam\_mm_mmm::in_array(mapRotation, level.mmmapname))
        mapRotation = codam\_mm_mmm::array_remove(mapRotation, level.mmmapname, true);
```

Replace (from line 502) with something like this:

```gsc
            case "map":
                if((i + 1) < mapRotation.size
                    && (lastgt != level.mmgametype || mapRotation[i + 1] != level.mmmapname)) {
                    _tmp[_tmp.size]["gametype"] = lastgt;
                    _tmp[_tmp.size - 1]["map"]  = mapRotation[i + 1];
                }

                i += 2;
            break;
```

Try it out and see if it works.

**Comment by ghost** [comment]
I thank you very much for your help, I tried after modifying `_mm_mapvote.gsc` doing exactly what you wrote.

On the duplicated map (zh_king) DM, here is how it looks now :

![current dm](https://user-images.githubusercontent.com/55389708/219137608-8b810f45-b0cc-4e76-a17f-7c9a870968b6.png)

When voted for the SD version, the game goes back to main menu without trying to load the map and displays this error : 

![dm to sd bomb error](https://user-images.githubusercontent.com/55389708/219138447-786c219d-6e8c-4731-9fe1-25352c5e3d45.png)

It seems there is no problem after entering `/reconnect`.
_________________

On the duplicated map SD, here is how it looks now :

![current sd](https://user-images.githubusercontent.com/55389708/219138824-89added8-ddb3-40f6-ba3d-7dc8c7241914.png)

When voted for the DM version, the team menu appears (like just arrived on the server), without loading the map.
It seems there is no gameplay problem.
_________________

I will try to fix that, if I succeed I will explain here how I done it.
Any info / ideas would be appreciated.

**Comment by ghost** [comment]
It looks that `StartGameType` is not called

**Comment by cato-a** [comment]
Different objects are precached in DM and SD gametype, so when it doesn't do a full map reload you get kicked out if those precaches are missing. It seems it doesn't do a full map reload when the rotation goes to same map.

It works from SD to DM because all the objects DM needs are precached in SD.
I guess you could try to precache it always and see if it works. And repeat for every other errors.

`precacheModel("xmodel/mp_bomb1_defuse");`

At least the code I made for you worked.

**Comment by ghost** [comment]
Thank you very much, it works now.

Here is how I done it : 
[mapvote_replay_othergametype.zip](https://github.com/cato-a/CoDaM_MiscMod/files/10756329/mapvote_replay_othergametype.zip)

I will probably create a repository if I make something powerful, such as reading maprotation instead of having to manually detect maps etc
