### ISSUE TITLE
Showdown winner not getting rewarded

### ISSUE THREAD

**Issue by ghost** [cato-a/CoDaM_MiscMod#7]
Hello
My `scr_mm_meleefight_winner` is enabled but winner is not getting rewarded
I can't find in the code where winner gets rewarded
I remember seeing a winner getting a M1 carbine on a server once
Did this feature got removed ?

**Comment by cato-a** [comment]
Hi Raphael, good to see you back.

In MiscMod the player is rewarded with a star in the scoreboard for one round in `sd`.

You can see the code here: https://github.com/cato-a/CoDaM_MiscMod/blob/0925241e64c83f84c40a701d4d1af4e0245931c4/___CoDaM_MiscMod/codam/miscmod.gsc#L651-L655

If you see any other rewards, then that is a customization done by the server owner.

**Comment by ghost** [comment]
Thank you Cato
